//! Encrypted firmware update image: header layout plus a streaming
//! AES-256-GCM implementation.
//!
//! Shared verbatim by three consumers, which is the point of the crate:
//!
//!   * `bootloader` — verifies and decrypts an image staged in slot B;
//!   * `imgtool` (host) — packs and encrypts a release binary;
//!   * host tests — check the two against each other and against
//!     vectors generated by an independent implementation.
//!
//! A format that lives in one place cannot drift between the packer and
//! the thing that has to boot from it.
//!
//! # Why the pieces are streaming
//!
//! The image is up to 120 KiB and the MCU has 32 KiB of RAM, so nothing
//! here may buffer a whole image. [`Verifier`] and [`Decryptor`] are fed
//! in chunks of the caller's choosing — the bootloader walks flash a
//! page at a time. [`Verifier`] handles partial blocks internally, so
//! chunk boundaries need not be multiples of 16.
//!
//! # Why verification is a separate pass
//!
//! GCM is encrypt-then-MAC, so the tag can only be checked once the
//! whole ciphertext has been read. Decrypting as we verify would mean
//! writing plaintext into the live application slot before knowing
//! whether the image is genuine — exactly the window an attacker wants.
//! The bootloader therefore runs [`Verifier`] over the staged image
//! first and only then runs [`Decryptor`] into slot A.

#![cfg_attr(not(test), no_std)]
#![forbid(unsafe_code)]

use aes::cipher::generic_array::GenericArray;
use aes::cipher::{BlockEncrypt, KeyInit, KeyIvInit, StreamCipher};
use aes::Aes256;
use ghash::universal_hash::UniversalHash;
use ghash::GHash;
use subtle::ConstantTimeEq;

/// Flash geometry shared by the bootloader, the application's linker
/// script and the host packer.
///
/// Kept here rather than in three linker scripts because a disagreement
/// between them is not a compile error — it is a device that bricks on
/// its first update. The `layout_is_consistent` test checks the numbers
/// add up to the part's flash size.
pub mod layout {
    /// STM32L151RC flash, 256 KiB.
    pub const FLASH_BASE: u32 = 0x0800_0000;
    pub const FLASH_LEN: u32 = 256 * 1024;

    /// Reserved for the bootloader. Also the application's vector-table
    /// address, which the bootloader writes into VTOR before jumping.
    pub const BOOTLOADER_LEN: u32 = 16 * 1024;

    /// Slot A runs the application; slot B stages an incoming image.
    /// Equal sizes, because after a swap B's contents must have fit in A.
    pub const SLOT_LEN: u32 = 120 * 1024;
    pub const SLOT_A: u32 = FLASH_BASE + BOOTLOADER_LEN;
    pub const SLOT_B: u32 = SLOT_A + SLOT_LEN;

    /// Erase granularity and write granularity of this part's flash.
    pub const PAGE: u32 = 256;
    pub const WRITE_SIZE: u32 = 4;

    /// Largest application this scheme can carry: slot B holds the
    /// header page as well as the ciphertext, so it — not slot A — is
    /// the binding constraint.
    pub const MAX_PAYLOAD: u32 = SLOT_LEN - super::HEADER_LEN as u32;
}

/// "UFWU" read as a little-endian u32 — uflowmeter firmware update.
pub const MAGIC: u32 = 0x5557_4655;

/// Bumped only for an incompatible header change. The bootloader
/// refuses anything it does not recognise rather than guessing.
pub const FORMAT_VERSION: u32 = 1;

/// Header size on flash. The header is padded out to a full erase page
/// so the ciphertext that follows starts page-aligned — the bootloader
/// can then walk it without a shifting offset.
pub const HEADER_LEN: usize = 256;

/// GCM nonce length. 96 bits is the only size for which J0 is defined
/// without a GHASH pass, and the only one this crate accepts.
pub const NONCE_LEN: usize = 12;

/// Full 128-bit GCM tag. Not truncated — there is no reason to.
pub const TAG_LEN: usize = 16;

/// AES-256.
pub const KEY_LEN: usize = 32;

/// Bytes of the header covered by the CRC: everything up to it.
const CRC_COVERED: usize = 44;

/// The authenticated-but-not-encrypted prefix: magic, format,
/// payload_len, image_version. Binding these into the tag is what stops
/// an attacker from replaying a genuine ciphertext under a forged
/// length or version.
const AAD_LEN: usize = 16;

// Header field offsets.
const OFF_MAGIC: usize = 0;
const OFF_FORMAT: usize = 4;
const OFF_PAYLOAD_LEN: usize = 8;
const OFF_IMAGE_VERSION: usize = 12;
const OFF_NONCE: usize = 16;
const OFF_TAG: usize = 28;
const OFF_CRC: usize = 44;

/// Why a header was rejected. Each variant is a distinct diagnosis, so
/// the bootloader can log which one it hit rather than a bare "bad
/// image" — the difference between a blank slot and a corrupt one
/// matters when a unit comes back from the field.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HeaderError {
    /// Buffer shorter than [`HEADER_LEN`].
    Truncated,
    /// No magic. Normal for an erased slot — this is "nothing staged",
    /// not "something is wrong".
    Magic,
    /// Magic matched but the format version is not [`FORMAT_VERSION`].
    Format,
    /// CRC mismatch: the header itself is damaged, most likely a write
    /// interrupted partway through.
    Crc,
    /// Payload length is zero, not a multiple of the flash write size,
    /// or larger than the destination slot.
    PayloadLen,
}

/// Parsed image header.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Header {
    /// Plaintext length in bytes. Ciphertext is the same length — GCM
    /// is a stream construction, so there is no padding.
    pub payload_len: u32,
    /// Monotonic image version, carried for logging and for a future
    /// anti-rollback check. Authenticated via the AAD.
    pub image_version: u32,
    pub nonce: [u8; NONCE_LEN],
    pub tag: [u8; TAG_LEN],
}

impl Header {
    /// Parse and sanity-check a staged header.
    ///
    /// `max_payload` is the usable size of the destination slot; a
    /// length beyond it is rejected here, before any of it is read, so
    /// a forged length cannot walk the bootloader off the end of flash.
    /// `write_size` is the flash write granularity — a payload that is
    /// not a whole number of write units could not be programmed
    /// without inventing padding bytes.
    pub fn parse(raw: &[u8], max_payload: u32, write_size: u32) -> Result<Header, HeaderError> {
        if raw.len() < HEADER_LEN {
            return Err(HeaderError::Truncated);
        }
        if u32_at(raw, OFF_MAGIC) != MAGIC {
            return Err(HeaderError::Magic);
        }
        if u32_at(raw, OFF_FORMAT) != FORMAT_VERSION {
            return Err(HeaderError::Format);
        }
        // CRC before any other field is trusted: a header torn by a
        // power cut mid-write can otherwise carry a plausible magic and
        // a garbage length.
        if u32_at(raw, OFF_CRC) != crc32(&raw[..CRC_COVERED]) {
            return Err(HeaderError::Crc);
        }

        let payload_len = u32_at(raw, OFF_PAYLOAD_LEN);
        if payload_len == 0 || payload_len > max_payload {
            return Err(HeaderError::PayloadLen);
        }
        if write_size == 0 || !payload_len.is_multiple_of(write_size) {
            return Err(HeaderError::PayloadLen);
        }

        let mut nonce = [0u8; NONCE_LEN];
        nonce.copy_from_slice(&raw[OFF_NONCE..OFF_NONCE + NONCE_LEN]);
        let mut tag = [0u8; TAG_LEN];
        tag.copy_from_slice(&raw[OFF_TAG..OFF_TAG + TAG_LEN]);

        Ok(Header {
            payload_len,
            image_version: u32_at(raw, OFF_IMAGE_VERSION),
            nonce,
            tag,
        })
    }

    /// Serialise into a full page, zero-padded.
    pub fn write(&self, out: &mut [u8; HEADER_LEN]) {
        out.fill(0);
        out[OFF_MAGIC..OFF_MAGIC + 4].copy_from_slice(&MAGIC.to_le_bytes());
        out[OFF_FORMAT..OFF_FORMAT + 4].copy_from_slice(&FORMAT_VERSION.to_le_bytes());
        out[OFF_PAYLOAD_LEN..OFF_PAYLOAD_LEN + 4].copy_from_slice(&self.payload_len.to_le_bytes());
        out[OFF_IMAGE_VERSION..OFF_IMAGE_VERSION + 4]
            .copy_from_slice(&self.image_version.to_le_bytes());
        out[OFF_NONCE..OFF_NONCE + NONCE_LEN].copy_from_slice(&self.nonce);
        out[OFF_TAG..OFF_TAG + TAG_LEN].copy_from_slice(&self.tag);
        let crc = crc32(&out[..CRC_COVERED]);
        out[OFF_CRC..OFF_CRC + 4].copy_from_slice(&crc.to_le_bytes());
    }

    /// The additional authenticated data bound into the tag.
    pub fn aad(&self) -> [u8; AAD_LEN] {
        let mut aad = [0u8; AAD_LEN];
        aad[0..4].copy_from_slice(&MAGIC.to_le_bytes());
        aad[4..8].copy_from_slice(&FORMAT_VERSION.to_le_bytes());
        aad[8..12].copy_from_slice(&self.payload_len.to_le_bytes());
        aad[12..16].copy_from_slice(&self.image_version.to_le_bytes());
        aad
    }
}

fn u32_at(buf: &[u8], off: usize) -> u32 {
    u32::from_le_bytes([buf[off], buf[off + 1], buf[off + 2], buf[off + 3]])
}

/// CRC-32/ISO-HDLC, computed bitwise.
///
/// Deliberately table-free: it runs over 44 bytes once per boot, so the
/// speed is irrelevant, and a 1 KiB table is not worth it in a 16 KiB
/// bootloader. This guards against a torn header only — the tag is what
/// guards against tampering.
pub fn crc32(data: &[u8]) -> u32 {
    let mut crc = 0xFFFF_FFFFu32;
    for &byte in data {
        crc ^= byte as u32;
        for _ in 0..8 {
            let mask = (crc & 1).wrapping_neg();
            crc = (crc >> 1) ^ (0xEDB8_8320 & mask);
        }
    }
    !crc
}

type Ctr = ctr::Ctr32BE<Aes256>;

/// Derive the two AES values GCM needs beyond the CTR keystream:
/// `H = E_K(0^128)` for GHASH, and `E_K(J0)` which masks the tag.
fn gcm_init(key: &[u8; KEY_LEN], nonce: &[u8; NONCE_LEN]) -> ([u8; 16], [u8; 16]) {
    let cipher = Aes256::new(GenericArray::from_slice(key));

    let mut h = GenericArray::clone_from_slice(&[0u8; 16]);
    cipher.encrypt_block(&mut h);

    // For a 96-bit nonce, J0 = nonce || 0x00000001.
    let mut j0 = [0u8; 16];
    j0[..NONCE_LEN].copy_from_slice(nonce);
    j0[15] = 1;
    let mut ek_j0 = GenericArray::clone_from_slice(&j0);
    cipher.encrypt_block(&mut ek_j0);

    (h.into(), ek_j0.into())
}

/// Streaming GCM authentication over a ciphertext.
///
/// Feed the ciphertext with [`update`](Self::update) in any chunking;
/// partial blocks are held internally until the next call. Then either
/// [`verify`](Self::verify) against the header's tag (bootloader) or
/// [`finish`](Self::finish) to produce one (packer).
pub struct Verifier {
    ghash: GHash,
    ek_j0: [u8; 16],
    residual: [u8; 16],
    residual_len: usize,
    ct_len: u64,
}

impl Verifier {
    /// Start authenticating an image described by `header`. The
    /// header's AAD is absorbed immediately; the tag field is not read,
    /// so this is equally usable while packing, when the tag is not yet
    /// known.
    pub fn new(key: &[u8; KEY_LEN], header: &Header) -> Self {
        let (h, ek_j0) = gcm_init(key, &header.nonce);
        let mut ghash = GHash::new(GenericArray::from_slice(&h));
        ghash.update_padded(&header.aad());
        Self {
            ghash,
            ek_j0,
            residual: [0u8; 16],
            residual_len: 0,
            ct_len: 0,
        }
    }

    /// Absorb the next span of ciphertext.
    pub fn update(&mut self, mut data: &[u8]) {
        self.ct_len += data.len() as u64;

        // Top up a partial block left by the previous call first.
        if self.residual_len > 0 {
            let take = core::cmp::min(16 - self.residual_len, data.len());
            self.residual[self.residual_len..self.residual_len + take]
                .copy_from_slice(&data[..take]);
            self.residual_len += take;
            data = &data[take..];
            if self.residual_len < 16 {
                // Input ran out before the block was complete. Return
                // here rather than falling through: the tail of this
                // function rewrites `residual_len` from what is left of
                // `data`, which is now empty, and would drop the bytes
                // just accumulated.
                return;
            }
            let block = GenericArray::clone_from_slice(&self.residual);
            self.ghash.update(&[block]);
            self.residual_len = 0;
        }

        // `as_chunks` hands back the whole blocks and the short tail in
        // one go, so the block count never has to be recomputed by hand.
        let (blocks, rest) = data.as_chunks::<16>();
        for chunk in blocks {
            let block = GenericArray::clone_from_slice(chunk);
            self.ghash.update(&[block]);
        }

        self.residual[..rest.len()].copy_from_slice(rest);
        self.residual_len = rest.len();
    }

    /// Produce the tag for everything absorbed so far.
    pub fn finish(mut self) -> [u8; TAG_LEN] {
        if self.residual_len > 0 {
            self.ghash
                .update_padded(&self.residual[..self.residual_len]);
        }

        // Final GHASH block: bit lengths of AAD and ciphertext, big-endian.
        let mut len_block = [0u8; 16];
        len_block[..8].copy_from_slice(&((AAD_LEN as u64) * 8).to_be_bytes());
        len_block[8..].copy_from_slice(&(self.ct_len * 8).to_be_bytes());
        self.ghash
            .update(&[GenericArray::clone_from_slice(&len_block)]);

        let s = self.ghash.finalize();
        let mut tag = [0u8; TAG_LEN];
        for i in 0..TAG_LEN {
            tag[i] = s[i] ^ self.ek_j0[i];
        }
        tag
    }

    /// Compare against the expected tag in constant time.
    ///
    /// Constant-time because a byte-at-a-time comparison that returns
    /// early leaks how much of a forged tag was correct, which is
    /// enough to construct a valid one a byte at a time.
    pub fn verify(self, expected: &[u8; TAG_LEN]) -> bool {
        let tag = self.finish();
        bool::from(tag.ct_eq(expected))
    }
}

/// Streaming CTR half of GCM.
///
/// Symmetric — the packer uses it to encrypt and the bootloader to
/// decrypt. Chunks must be applied in order; each call continues the
/// keystream where the last left off.
pub struct Decryptor {
    ctr: Ctr,
}

impl Decryptor {
    pub fn new(key: &[u8; KEY_LEN], header: &Header) -> Self {
        // GCM reserves counter 1 (J0) for the tag mask, so the payload
        // keystream starts at 2.
        let mut iv = [0u8; 16];
        iv[..NONCE_LEN].copy_from_slice(&header.nonce);
        iv[15] = 2;
        Self {
            ctr: Ctr::new(GenericArray::from_slice(key), GenericArray::from_slice(&iv)),
        }
    }

    /// XOR the next span of the keystream over `buf`, in place.
    pub fn apply(&mut self, buf: &mut [u8]) {
        self.ctr.apply_keystream(buf);
    }
}

#[cfg(test)]
mod tests;
